from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path
from typing import Annotated, List, Optional, Tuple

from pydantic import BaseModel, Field, field_validator

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))
from model_client import ModelClient, ModelClientError  # noqa: E402


class InspectionSubmission(BaseModel):
    """Shape of the form data script.js submits."""

    facility_name: str
    site_address: str
    inspector_email: str
    inspection_summary: str
    program_element: str


# Each tag must be a string 3-30 characters long (enforced per-item, not just list length).
Tag = Annotated[str, Field(min_length=3, max_length=30)]


class PlannerOutput(BaseModel):
    tags: List[Tag] = Field(
        ...,
        min_length=3,
        max_length=3,
        description="Exactly 3 tags, each a 3-30 character topical concept/theme",
    )
    draft_summary: str = Field(..., description="One sentence, at most 25 words")

    @field_validator("draft_summary")
    @classmethod
    def _draft_summary_word_limit(cls, value: str) -> str:
        word_count = len(value.split())
        if word_count > 25:
            raise ValueError(f"draft_summary must be at most 25 words, got {word_count}")
        return value


class RevisedOutput(BaseModel):
    tags: List[str] = Field(..., min_length=3, max_length=3, description="Final tags, exactly three")
    summary: str = Field(..., description="Final one-sentence summary, at most 25 words")


class ReviewerOutput(BaseModel):
    approved: bool = Field(..., description="Whether the Planner's draft passed all criteria as-is")
    feedback: str = Field(default="", description="Reasoning for rejection if applicable, otherwise empty")
    revised_output: RevisedOutput


class PublishOutput(BaseModel):
    title: str
    tags: List[str]
    summary: str
    approved_by_reviewer: bool


PLANNER_SYSTEM = """You are the Planner Agent, the first stage in a highly structured text processing pipeline.
Your job is to analyze the user-provided "Title" and "Content" and generate a foundational draft.

You must extract the core concepts and summarize the text according to these strict rules:
1. Identify the 3 most important, specific topical concepts or themes present in the text.
2. Draft a concise, one-sentence summary of the text that must be 25 words or fewer.
3. Your output must strictly be raw, valid JSON containing only the keys "tags" and "draft_summary". Do not include markdown formatting, backticks, or any conversational prose.

Expected JSON schema format:
{
  "tags": ["tag1", "tag2", "tag3"],
  "draft_summary": "Your concise summary statement goes here."
}"""

REVIEWER_SYSTEM = """You are the Reviewer Agent, the quality assurance gatekeeper in a text processing pipeline.
Your job is to critically evaluate the draft generated by the Planner Agent against the original user input ("Title" and "Content").

You must enforce compliance based on the following criteria:
1. Tag Accuracy: Verify that exactly 3 tags are provided and that they directly represent the core topics of the input.
2. Word Count Discipline: Count the words in the draft summary. It MUST be 25 words or fewer.
3. Factuality: Ensure the summary introduces no outside information or hallucinated facts.

Your output must strictly be raw, valid JSON containing only the keys "approved", "feedback", and "revised_output". Do not include markdown formatting, backticks, or any conversational prose.

- If the draft passes all criteria: Set "approved" to true, keep "feedback" empty, and populate "revised_output" with the planner's original data.
- If the draft fails (e.g., summary too long, bad tags): Set "approved" to false, provide precise architectural instructions in "feedback", and output a fully corrected, compliant version in "revised_output" (ensuring the new summary is 25 words or fewer).

Expected JSON schema format:
{
  "approved": true/false,
  "feedback": "Reasoning for rejection if applicable, otherwise empty.",
  "revised_output": {
    "tags": ["tag1", "tag2", "tag3"],
    "summary": "The final verified summary statement of 25 words or fewer."
  }
}"""


def run_planner(client: ModelClient, title: str, content: str) -> PlannerOutput:
    user = f'Title: "{title}"\n\nContent:\n{content}'
    return client.call(system=PLANNER_SYSTEM, user=user, output_format=PlannerOutput)


def run_reviewer(client: ModelClient, title: str, content: str, draft: PlannerOutput) -> ReviewerOutput:
    user = (
        f'Title: "{title}"\n\nContent:\n{content}\n\n'
        f"Planner's draft (JSON):\n{draft.model_dump_json()}"
    )
    return client.call(system=REVIEWER_SYSTEM, user=user, output_format=ReviewerOutput)


def finalize(title: str, review: ReviewerOutput) -> PublishOutput:
    """ finalization step - no model call, just assembles the Publish record."""
    return PublishOutput(
        title=title,
        tags=review.revised_output.tags,
        summary=review.revised_output.summary,
        approved_by_reviewer=review.approved,
    )


def build_document(submission: InspectionSubmission) -> Tuple[str, str]:
    """Turn a form submission into the title/content pair the agents read."""
    title = f"{submission.program_element.title()} - {submission.facility_name}"
    content = (
        f"Facility: {submission.facility_name}\n"
        f"Site Address: {submission.site_address}\n"
        f"Program Element: {submission.program_element}\n"
        f"Inspector: {submission.inspector_email}\n"
        f"Findings: {submission.inspection_summary}"
    )
    return title, content


def run_pipeline(
    client: ModelClient, submission: InspectionSubmission
) -> Tuple[PlannerOutput, ReviewerOutput, PublishOutput]:
    """Run Planner -> Reviewer -> finalize for one submission.

    Raises `ModelClientError` if the local model is unreachable or never
    returns valid JSON - callers (CLI, FastAPI) decide how to surface that.
    """
    title, content = build_document(submission)
    draft = run_planner(client, title, content)
    review = run_reviewer(client, title, content, draft)
    publish = finalize(title, review)
    return draft, review, publish


def _print_step(name: str, payload: BaseModel, elapsed_ms: Optional[int] = None) -> None:
    header = f"{name} ({elapsed_ms} ms)" if elapsed_ms is not None else name
    print("=" * 60)
    print(header)
    print("=" * 60)
    print(json.dumps(payload.model_dump(), indent=2))
    print()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run the Planner -> Reviewer -> Publish pipeline on one inspection submission."
    )
    parser.add_argument("--facility-name", default="FA0206933 - YUMMY KITCHEN")
    parser.add_argument("--site-address", default="1711 BRANHAM LN A9, SAN JOSE, CA 95118")
    parser.add_argument("--inspector-email", default="inspector@countyhealth.gov")
    parser.add_argument("--program-element", default="ROUTINE HEALTH INSPECTION")
    parser.add_argument(
        "--inspection-summary",
        default=(
            "Observed improper cold-holding temperatures in the walk-in refrigerator and missing employee handwashing signage near the prep sink. Manager corrected the refrigerator setting on-site; signage to be posted within 48 hours."
        ),
    )
    return parser.parse_args()


def main() -> None:
   
    args = parse_args()
    submission = InspectionSubmission(
        facility_name=args.facility_name,
        site_address=args.site_address,
        inspector_email=args.inspector_email,
        program_element=args.program_element,
        inspection_summary=args.inspection_summary,
    )

    try:
        client = ModelClient()
        title, content = build_document(submission)

        t0 = time.time()
        draft = run_planner(client, title, content)
        planner_ms = int((time.time() - t0) * 1000)

        t0 = time.time()
        review = run_reviewer(client, title, content, draft)
        reviewer_ms = int((time.time() - t0) * 1000)

        publish = finalize(title, review)
    except ModelClientError as exc:
        print(f"Agent pipeline failed: {exc}", file=sys.stderr)
        sys.exit(1)

    _print_step("PLANNER", draft, planner_ms)
    _print_step("REVIEWER", review, reviewer_ms)
    _print_step("PUBLISH", publish)


if __name__ == "__main__":
    main()
