"""Stateful Planner/Reviewer agent graph, built with LangGraph.

This reuses the same prompts, Pydantic schemas, and ModelClient adapter as
the linear pipeline in agents_demo.py, but wires them into an explicit
Supervisor -> Planner/Reviewer -> Supervisor/END graph instead of a fixed
Python call sequence. A rejection clears planner_proposal back to None,
which is what sends control back through the Planner (with the Reviewer's
feedback attached) on the next Supervisor visit, rather than the Reviewer
just re-grading its own patched-up draft in place. This repeats until the
Reviewer approves or the graph hits a turn-count safety cap.

Graph shape:

    START -> Supervisor -> [no planner_proposal yet]  -> Planner  -> Supervisor
                         -> [has planner_proposal]     -> Reviewer -> [rejected: proposal cleared] -> Supervisor
                                                                    -> [approved]                   -> END
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Optional, TypedDict

from langgraph.graph import END, StateGraph

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))
from agents_demo import (  # noqa: E402
    InspectionSubmission,
    PlannerOutput,
    ReviewerOutput,
    build_document,
)
from model_client import ModelClient, ModelClientError  # noqa: E402

# Loops end once the Reviewer approves, or after this many Supervisor visits -
# whichever comes first. Without this cap a model that never converges to
# "approved": true would loop the graph forever. Each Planner<->Reviewer round
# trip costs 2 turns (one Supervisor visit before each node), so this allows
# up to 4 full rounds before cutting off - generous enough that the cap
# rarely bites mid-round on a realistic run.
MAX_TURNS = 8

PLANNER_SYSTEM = """You are the Planner Agent, the first stage in a highly structured text processing pipeline.
Your job is to analyze the user-provided "Title" and "Content" and generate a foundational draft.

You must extract the core concepts and summarize the text according to these strict rules:
1. Identify the 3 most important, specific topical concepts or themes present in the text.
2. Draft a concise, one-sentence summary of the text that must be 25 words or fewer.
3. Your output must strictly be raw, valid JSON containing only the keys "tags" and "draft_summary". Do not include markdown formatting, backticks, or any conversational prose.

Expected JSON schema format:
{
  "tags": ["tag1", "tag2", "tag3"],
  "draft_summary": "Your concise summary statement goes here."
}"""

REVIEWER_SYSTEM_STRICT = """You are the Reviewer Agent, the quality assurance gatekeeper in a text processing pipeline.
Your job is to critically evaluate the draft generated by the Planner Agent against the original user input ("Title" and "Content").

You must enforce compliance based on the following criteria:
1. Tag Accuracy: Verify that exactly 3 tags are provided and that they directly represent the core topics of the input.
2. Word Count Discipline: Count the words in the draft summary. It MUST be 25 words or fewer.
3. Factuality: Ensure the summary introduces no outside information or hallucinated facts.

Your output must strictly be raw, valid JSON containing only the keys "approved", "feedback", and "revised_output". Do not include markdown formatting, backticks, or any conversational prose.

- If the draft passes all criteria: Set "approved" to true, keep "feedback" empty, and populate "revised_output" with the planner's original data.
- If the draft fails (e.g., summary too long, bad tags): Set "approved" to false, provide precise correction instructions in "feedback", and output a fully corrected, compliant version in "revised_output" (ensuring the new summary is 25 words or fewer).

Expected JSON schema format:
{
  "approved": true/false,
  "feedback": "Reasoning for rejection if applicable, otherwise empty.",
  "revised_output": {
    "tags": ["tag1", "tag2", "tag3"],
    "summary": "The final verified summary statement of 25 words or fewer."
  }
}"""

# Used when AgentState["strict"] is False: same JSON contract, but tolerant
# of minor overage rather than rejecting on the first small violation.
REVIEWER_SYSTEM_LENIENT = REVIEWER_SYSTEM_STRICT.replace(
    "2. Word Count Discipline: Count the words in the draft summary. It MUST be 25 words or fewer.",
    "2. Word Count Discipline: The draft summary should be about 25 words. Minor overage (a few words) is "
    "acceptable and should not by itself cause rejection.",
).replace(
    "1. Tag Accuracy: Verify that exactly 3 tags are provided and that they directly represent the core topics of the input.",
    "1. Tag Accuracy: Verify that exactly 3 tags are provided and are reasonably related to the core topics of "
    "the input - they do not need to be the single best possible choice.",
)


class AgentState(TypedDict):
    title: str
    content: str
    email: str
    strict: bool
    task: str
    llm: ModelClient
    planner_proposal: Optional[dict]
    reviewer_feedback: Optional[dict]
    turn_count: int


def planner_node(state: AgentState) -> dict:
    """Calls the LLM (via state['llm']) to draft tags + a summary.

    On a fresh run this is a first attempt from just title/content. On a
    retry after a rejection OR a schema validation failure, reviewer_feedback
    carries the prior critique - fold it in so the new draft actually
    addresses what was wrong, instead of the Planner blindly regenerating
    the same thing. (There's no separate "validation_error" field in
    AgentState - a caught ModelClientError is reported through the same
    reviewer_feedback slot a Reviewer rejection uses, since both cases mean
    the same thing to this node: "the last draft wasn't good enough, here's
    why, try again.")"""
    feedback = state.get("reviewer_feedback")
    feedback_note = ""
    if feedback and not feedback.get("approved") and feedback.get("feedback"):
        feedback_note = (
            f'\n\nA previous draft was rejected with this feedback - '
            f'address it in this new draft:\n{feedback["feedback"]}'
        )

    user = (
        f'Task: {state["task"]}\n'
        f'Title: "{state["title"]}"\n'
        f'Submitter: {state["email"]}\n\n'
        f'Content:\n{state["content"]}{feedback_note}'
    )
    try:
        draft: PlannerOutput = state["llm"].call(
            system=PLANNER_SYSTEM, user=user, output_format=PlannerOutput
        )
    except ModelClientError as exc:
        # Schema validation (exactly 3 tags, 3-30 chars each, <=25 words) keptfailing even after ModelClient's own internal JSON-repair retries.
        # Don't let this crash the graph: report it like a rejection so the *next* Planner turn sees exactly what was invalid and can correct for it. planner_proposal is left untouched (still None at this point), 
        # so router_logic's "no proposal -> planner" branch fires again - bounded by the same MAX_TURNS cap as every other loop, so a Planner that can never produce valid JSON still terminates.
        return {
            "reviewer_feedback": {
                "approved": False,
                "feedback": f"[SCHEMA VALIDATION FAILED] Your last output was rejected: {exc}",
            },
        }
    return {"planner_proposal": draft.model_dump()}


def reviewer_node(state: AgentState) -> dict:
    """Calls the LLM to grade planner_proposal.

    On approval, planner_proposal is finalized to the Reviewer's
    revised_output. On rejection, planner_proposal is cleared back to None -
    that's what makes router_logic's "no proposal -> Planner" branch fire on
    the next Supervisor visit, actually sending control back to the Planner
    with the feedback attached, instead of just re-reviewing in place."""
    system = REVIEWER_SYSTEM_STRICT if state["strict"] else REVIEWER_SYSTEM_LENIENT
    user = (
        f'Task: {state["task"]}\n'
        f'Title: "{state["title"]}"\n'
        f'Submitter: {state["email"]}\n\n'
        f'Content:\n{state["content"]}\n\n'
        f'Planner\'s draft (JSON):\n{json.dumps(state["planner_proposal"])}'
    )
    review: ReviewerOutput = state["llm"].call(
        system=system, user=user, output_format=ReviewerOutput
    )
    return {
        "reviewer_feedback": review.model_dump(),
        "planner_proposal": review.revised_output.model_dump() if review.approved else None,
    }


def supervisor_node(state: AgentState) -> dict:
    """Bookkeeping only - no LLM call, no routing decision."""
    return {"turn_count": state["turn_count"] + 1}


def router_logic(state: AgentState) -> str:
    """Reads state only; both conditional edges below reuse this function -
    the graph wiring decides what "planner"/"reviewer" mean at each edge."""
    feedback = state.get("reviewer_feedback")
    if feedback is not None and feedback.get("approved"):
        return END
    if state["turn_count"] >= MAX_TURNS:
        return END
    if not state.get("planner_proposal"):
        return "planner"
    return "reviewer"


def build_graph():
    graph = StateGraph(AgentState)
    graph.add_node("supervisor", supervisor_node)
    graph.add_node("planner", planner_node)
    graph.add_node("reviewer", reviewer_node)

    graph.set_entry_point("supervisor")

    # Supervisor -> (no proposal -> Planner | has proposal -> Reviewer)
    graph.add_conditional_edges(
        "supervisor",
        router_logic,
        {"planner": "planner", "reviewer": "reviewer", END: END},
    )
    graph.add_edge("planner", "supervisor")

    # Reviewer -> (issues -> back to Supervisor | no issues -> END)
    graph.add_conditional_edges(
        "reviewer",
        router_logic,
        {"planner": "supervisor", "reviewer": "supervisor", END: END},
    )

    return graph.compile()


def _initial_state(
    client: ModelClient,
    submission: InspectionSubmission,
    *,
    strict: bool,
    task: str,
) -> AgentState:
    title, _ = build_document(submission)
    return {
        "title": title,
        "content": submission.inspection_summary,
        "email": submission.inspector_email,
        "strict": strict,
        "task": task,
        "llm": client,
        "planner_proposal": None,
        "reviewer_feedback": None,
        "turn_count": 0,
    }


def run_agent_graph(
    client: ModelClient,
    submission: InspectionSubmission,
    *,
    strict: bool = True,
    task: str = "Summarize the inspection findings and extract 3 topical tags.",
) -> AgentState:
    initial_state = _initial_state(client, submission, strict=strict, task=task)
    app = build_graph()
    return app.invoke(initial_state)


def stream_agent_graph(
    client: ModelClient,
    submission: InspectionSubmission,
    *,
    strict: bool = True,
    task: str = "Summarize the inspection findings and extract 3 topical tags.",
) -> AgentState:
    """Same as run_agent_graph, but drives the graph with .stream() instead of
    .invoke() and prints each node's incremental update as it executes - this
    is what actually shows the Supervisor -> Planner/Reviewer -> Supervisor/END
    hops happening, one at a time, instead of only the final result."""
    initial_state = _initial_state(client, submission, strict=strict, task=task)
    app = build_graph()

    final_state: dict = dict(initial_state)
    for step_num, step in enumerate(app.stream(initial_state), start=1):
        for node_name, update in step.items():
            print(f"--- step {step_num}: {node_name} ---")
            print(json.dumps(update, indent=2, default=str))
            final_state.update(update)
    return final_state  # type: ignore[return-value]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run the Supervisor/Planner/Reviewer LangGraph agent on one inspection submission."
    )
    parser.add_argument("--facility-name", default="FA0206933 - YUMMY KITCHEN")
    parser.add_argument("--site-address", default="1711 BRANHAM LN A9, SAN JOSE, CA 95118")
    parser.add_argument("--inspector-email", default="inspector@countyhealth.gov")
    parser.add_argument("--program-element", default="ROUTINE HEALTH INSPECTION")
    parser.add_argument(
        "--inspection-summary",
        default=(
            "Observed improper cold-holding temperatures in the walk-in refrigerator and missing employee "
            "handwashing signage near the prep sink. Manager corrected the refrigerator setting on-site; "
            "signage to be posted within 48 hours."
        ),
    )
    parser.add_argument("--lenient", action="store_true", help="Run the Reviewer in lenient mode (strict=False).")
    parser.add_argument(
        "--task",
        default="Summarize the inspection findings and extract 3 topical tags.",
        help="Free-text task description passed to both the Planner and Reviewer prompts.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    submission = InspectionSubmission(
        facility_name=args.facility_name,
        site_address=args.site_address,
        inspector_email=args.inspector_email,
        program_element=args.program_element,
        inspection_summary=args.inspection_summary,
    )

    try:
        client = ModelClient()
        final_state = stream_agent_graph(client, submission, strict=not args.lenient, task=args.task)
    except ModelClientError as exc:
        print(f"Agent graph failed: {exc}", file=sys.stderr)
        sys.exit(1)

    print("=" * 60)
    print(f"Finished after {final_state['turn_count']} supervisor turn(s)")
    print("=" * 60)
    print(json.dumps(
        {
            "planner_proposal": final_state["planner_proposal"],
            "reviewer_feedback": final_state["reviewer_feedback"],
        },
        indent=2,
    ))


if __name__ == "__main__":
    main()
