"""Build reports/hw04/METRICS.md from the raw files (no re-measurement).

    python code/hw04/compute_metrics.py
"""
from __future__ import annotations

import csv
import json
from pathlib import Path

from hw04_config import LOCAL_MODEL, RAW_DIR, REPORT_DIR, SEED


def read_csv(path: Path) -> list[dict]:
    with path.open(encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def md_table(headers: list[str], rows: list[list]) -> str:
    out = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    out += ["| " + " | ".join(str(c) for c in row) + " |" for row in rows]
    return "\n".join(out)


def nplus1_section(tag: str = "") -> str:
    suffix = f"_{tag}" if tag else ""
    path = RAW_DIR / f"nplus1_summary{suffix}.csv"
    if not path.exists():
        return ""
    rows = read_csv(path)
    table = md_table(
        ["Page size", "Version", "SQL stmts/req", "p50 (ms)", "p95 (ms)", "p99 (ms)", "server p50 (ms)", "records / violations returned"],
        [[r["page_size"], r["version"], r["sql_stmts_per_req"], r["p50_ms"], r["p95_ms"], r["p99_ms"],
          r["server_p50_ms"], f"{r['records_returned']} / {r['violations_returned']}"] for r in rows],
    )
    speed = md_table(
        ["Page size", "naive p50 (ms)", "fixed p50 (ms)", "Speed-up (naive p50 / fixed p50)", "Queries saved/req", "Identical data"],
        [[n["page_size"], n["p50_ms"], f["p50_ms"], f"{float(n['p50_ms']) / float(f['p50_ms']):.2f}x",
          int(n["sql_stmts_per_req"]) - int(f["sql_stmts_per_req"]), n["same_data_both_versions"]]
         for n, f in zip(rows[0::2], rows[1::2])],
    )
    return f"{table}\n\n{speed}\n"


def explain_section() -> str:
    path = RAW_DIR / "explain_before_after.json"
    if not path.exists():
        return ""
    data = json.loads(path.read_text(encoding="utf-8"))
    rows = []
    for name in data["queries"]:
        for label in ("before", "after"):
            plan = data[label]["plans"][name]["rows"][0]
            rows.append([name, label, plan.get("type"), plan.get("possible_keys"), plan.get("key"),
                         plan.get("rows"), plan.get("Extra")])
    return md_table(["Query", "State", "type", "possible_keys", "key", "rows (est.)", "Extra"], rows) + "\n"


def rag_section() -> str:
    path = RAW_DIR / "rag_evaluation_summary.csv"
    if not path.exists():
        return ""
    summary = read_csv(path)
    headers = list(summary[0].keys())
    out = [md_table(headers, [[r[h] for h in headers] for r in summary])]

    evals = read_csv(RAW_DIR / "rag_evaluation_table.csv")
    headers = list(evals[0].keys())
    out.append("\nPer question and configuration:\n")
    out.append(md_table(headers, [[r[h] if r[h] != "" else "n/a" for h in headers] for r in evals]))

    sweep = read_csv(RAW_DIR / "rag_k_sweep.csv")
    out.append("\nk-sweep (configs B and C):\n")
    out.append(md_table(
        ["Question", "k", "Config", "Retrieved chunk_ids", "Relevant / irrelevant retrieved", "Kept in prompt",
         "Context tokens", "Correct answer", "Grounded"],
        [[r["question_id"], r["top_k"], r["config"], r["retrieved_chunk_ids"].replace(";", "; "),
          f"{r['n_relevant_retrieved']} / {r['n_irrelevant_retrieved']}", r["context_chunk_ids"].replace(";", "; "),
          r["context_tokens"], r["correct_answer"], r["grounded"]] for r in sweep],
    ))
    return "\n".join(out) + "\n"


def main() -> None:
    seed_summary = json.loads((RAW_DIR / "seed_summary.json").read_text(encoding="utf-8"))
    parts = [
        "# HW4 Metrics",
        "",
        "Generated by `python code/hw04/compute_metrics.py` from the files in `reports/hw04/raw/`.",
        "",
        "## Part 3 - N+1 measurement (180 measured requests)",
        "",
        f"Data: {seed_summary['inspections']} inspections, {seed_summary['violations']} violations "
        f"(SEED={SEED}, sha256 {seed_summary['generated_data_sha256'][:16]}...). Requests hit offset 0; "
        "latency is client round-trip (`time.perf_counter` around the HTTP call, localhost), 30 measured "
        "requests per row after 3 warm-ups, naive/fixed interleaved. SQL stmts/req counts every statement the "
        "endpoint sent to MySQL (SQLAlchemy `before_cursor_execute`), excluding the session-cookie lookup. "
        "p99 of 30 samples is interpolated between the two slowest requests. Measured before the index was added.",
        "",
        "Raw data: `raw/nplus1_requests.csv` / `.json`; summary: `raw/nplus1_summary.csv`.",
        "",
        nplus1_section(),
    ]
    with_index = nplus1_section("with_index")
    if with_index:
        parts += ["### Supplementary: same benchmark after adding the index", "",
                  "Raw data: `raw/nplus1_requests_with_index.csv`.", "", with_index]
    parts += ["## Part 3.8 - EXPLAIN before/after `ix_violations_inspection_id`", "",
              "Full output (including EXPLAIN ANALYZE): `raw/explain_before_after.txt`.", "", explain_section(),
              "## Part 4 - RAG evaluation", "",
              f"Model `{LOCAL_MODEL}` (Ollama, temperature 0, seed {SEED}); embeddings `BAAI/bge-small-en-v1.5`; "
              "chunk_size 500 / overlap 50; top_k 3 unless noted. Scoring rules are automatic and documented in "
              "`evaluate()` in `code/hw04/rag.py`.", "", rag_section()]
    (REPORT_DIR / "METRICS.md").write_text("\n".join(parts), encoding="utf-8")
    print((REPORT_DIR / "METRICS.md").read_text(encoding="utf-8"))


if __name__ == "__main__":
    main()
